server:
  port: 8080


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ohgiraffers
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

